export const JOB_TYPES = [
    "Kapalı Alan",
    "Asitle Yıkama",
    "Elektrik Testi ve Montaj",
    "Elle Taşlama",
    "Boya Uygulaması",
    "Raspa Uygulaması",
    "Bakım - Onarım",
    "Panel & İzolasyon",
    "Makine Tesit ve Montajı",
    "Sıcak iş",
    "Yüksekte çalışma",
    "Su jeti Uygulaması",
    "Mobilya Montajı",
    "Kaynak Film",
    "Karbon taşlama",
    "Kaynak",
    "Taşlama",
    "Kesme",
    "Tavlama",
    "Serh Lehim",
    "İskelelerde Çalışma",
    "İskele Kurulumu - Sökümü",
    "Montaj (Boru,Çelik)",
    "Basınç Testi",
    "Yakıt Alma",
    "Kaldırma Operasyonları",
    "Diğer"
];

export const HAZARDS = [
    "Yanıcı Maddeler",
    "Sıcak Cüruf, Sıçrak veya Kıvılcımlar",
    "Kimyasal Maddelere Maruziyet",
    "Hareketli Makineler",
    "Kötü Hava Koşulları",
    "Parlayıcı - Patlayıcı Atmosfer",
    "Elektrik Akımına Kapılma",
    "Statik Elektrik",
    "Radyoaktif Maruziyet",
    "Düşme Tehlikesi",
    "Basınçlı Sıvı yada Gaz",
    "Boru - Hortum Bağlatılarında Sızıntı",
    "Malzeme-Parça Düşmesi",
    "Uçuşan Parçacıklar",
    "Diğer"
];

export const PPE_REQUIREMENTS = [
    "Göz koruyucu",
    "Toz maskesi",
    "Emniyet Kemeri",
    "Yüz Vizörü",
    "Kulak koruyucusu",
    "İş Elbisesi",
    "Can yeleği",
    "Çelik Uçlu Ayakkabı",
    "Yarım Yüz maskesi",
    "Koruyucu Eldiven",
    "Ty- Vek İş Elbisesi",
    "Baret",
    "Kaynakçı Maskesi",
    "Diğer"
];

export const PRECAUTIONS = [
    "Havalandırma",
    "Zemin Boşlukları Kapatıldı",
    "Test Yapılan Tankları Etiketleme",
    "Elektriğin Kesilmesi, Kilitleme & Etiketleme",
    "Kimyasalları Temizleme",
    "Kaldırma, Çektirme Ekipman Kontrol",
    "Hortum ve Bağlantıların Kontrolü",
    "Alev Alıcı/Yanıcı Maddelerin Uzaklaştırılması",
    "Acil Durumlarda Ne Yapılacağı Biliniyor",
    "Gaz ölçümü",
    "Yanmaz Bez İle Örtme",
    "Birbirini Etkileyecek İşlerin Gözden Geçirilmesi",
    "Uygun Giriş/Çıkış",
    "Topraklama / Elektrikli İş Ekipmanlarının Kontrolü",
    "Yeterli Aydınlatma (24V)",
    "Ekipman Koruyucuları Mevcuttur",
    "İlgili Talimatların Uygulanması",
    "Çalışılacak Alandaki İskelenin Kontrolü",
    "Kaynak Filmi İşleminde Emniyet Mesafesinin Korunması",
    "Gözlemci",
    "Komşu Alanların Kontrolü",
    "Tehlikeler ve Alınması Gereken Önlemler Çalışanlarla Paylaşıldı",
    "Yangına Müdahale Ekipmanları(Yangın Söndürücü, yangın Hortumu vb.)",
    "Sağlık ve Güvenlik İşaretleri",
    "Keskin ve Sivri uçların Temizlenmesi",
    "Uygun Geçici/Kalıcı Korkuluklar",
    "Çalışma Alanını Emniyet Şeridi ile Çevirme",
    "Diğer"
];
